
name: Score Submission

on:
  workflow_dispatch:
  push:
    paths:
      - submissions/**

jobs:
  evaluate:
    runs-on: ubuntu-latest

    env:
      PRIVATE_Y: ${{ secrets.LABELS }}
      PRIVATE_TEST_MASK_CHALLENGE: ${{ secrets.TEST_MASK_CHALLANGE }}
      PRIVATE_TEST_MASK: ${{ secrets.TEST_MASK }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Check submission CSV exists
      run: |
        if [ ! -f submissions/submission.csv ]; then
          echo "Error: submissions/submission.csv not found!"
          exit 1
        fi

    - name: Evaluate submission
      run: |
        python evaluate.py

    - name: Upload leaderboard score
      uses: actions/upload-artifact@v4
      with:
        name: leaderboard_score
        path: score.csv
